export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVER_INGREDIENT = 'REMOVE_INGREDIENT';

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const FETCH_USER = 'FETCH_USER'
export const SELECTED_USER = 'SELECTED_USER'
export const EDIT_USER = 'EDIT_USER'
export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const CREATE_COACH_START = 'CREATE_COACH_START'
export const CREATE_COACH_SUCCESS = 'CREATE_COACH_SUCCESS'
export const CREATE_COACH_FAIL = 'CREATE_COACH_FAIL'

